name: Build Sisyphus firmware

on:
  push:
    paths:
      - "src/**"
  pull_request:
    paths:
      - "src/**"
  workflow_dispatch:

jobs:
  firmware_build:
    name: Build Sisyphus firmware
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        config:
          - name: "Default"
            cmake_args: ""
            suffix: "pico"
          - name: "Eternity"
            cmake_args: "-DUSE_ETERNITY=ON"
            suffix: "pico-eternity"
          - name: "SisyFOSS Beta - Eternity"
            cmake_args: "-DPICO_BOARD=plajta_sisyfoss_beta -DUSE_ETERNITY=ON"
            suffix: "pico-eternity"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Get Git SHA
        id: vars
        run: echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build firmware - ${{ matrix.config.name }}
        id: build
        uses: samyarsadat/Pico-Build-Action@v1.3.0
        with:
          source_dir: "src"
          output_ext: "*.uf2 sisyphus.elf sisyphus.elf.map sisyphus.bin"
          cmake_args: "-DGIT_COMMIT_SHA=${{ env.GIT_SHA }} ${{ matrix.config.cmake_args }}"

      - name: Upload Build Artifacts - ${{ matrix.config.name }}
        uses: actions/upload-artifact@v4
        with:
          name: output_bins_${{ matrix.config.suffix }}
          path: ${{ steps.build.outputs.output_dir }}
