name: Build Sisyphus firmware

on:
  push:
    paths:
      - "src/**"
  pull_request:
    paths:
      - "src/**"
  workflow_dispatch:

jobs:
  firmware_build:
    name: Build sisyphus firmware
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Get Git SHA
        id: vars
        run: echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build firmware
        id: build
        uses: samyarsadat/Pico-Build-Action@v1.3.0
        with:
          source_dir: "src"
          output_ext: "*.uf2 sisyphus.elf sisyphus.elf.map sisyphus.bin"
          cmake_args: "-DGIT_COMMIT_SHA=${{ env.GIT_SHA }}"

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: workspace_artifacts
          path: ${{ steps.build.outputs.output_dir }}
